# File: src\monitoring\prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Metrics système (CPU, RAM, disque, réseau)
  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "localhost:9100"

  # Metrics FastAPI
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "localhost:8000"
