services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health | grep -E 'yellow|green'"]
      interval: 10s
      timeout: 10s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      SERVER_PUBLICBASEURL: "http://3.252.196.177:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"

  app:
    build: .
    command: python main.py
    environment:
      ES_HOST: http://elasticsearch:9200
    volumes:
      - ./datas:/app/datas
    depends_on:
      elasticsearch:
        condition: service_healthy
